### ISSUE TITLE
Where should cache logic go?

### ISSUE THREAD

**Issue by gentra** [zainul/xs#1]
When first seeing `repository` package on this project. I thought there will be a concrete struct in there which handles the `cache` and `database` logic, but it seems it only provides the Repository interface which to be used by the `database` struct.

Where should the cache logic go? My first thought was that we should create a repository struct which handles both the invokes the cache and database, but it turns out that it violates the Single-Responsibility principle.

There's an idea on this stackoverflow thread where we should create a proxy or strategy class https://stackoverflow.com/a/7805942
https://ardalis.com/introducing-the-cachedrepository-pattern
Maybe we can try to use that here?

**Comment by zainul** [comment]
Actually i am little bit violation about cache but the code not commit yet , 
I have multiple cache in `in memory cache` , `local-cache` and `key value store`
But thank you for the suggestion about article i will read and try hehe

**Comment by zainul** [comment]
I will closed if no longer issue with PR #2 
Feel free to re open :)
